/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.biosislite.vistas.inventario;

import com.biosis.biosislite.controladores.inventario.BienInventarioControlador;
import com.biosis.biosislite.controladores.inventario.MovimientoControlador;
import com.biosis.biosislite.entidades.escalafon.Departamento;
import com.biosis.biosislite.entidades.escalafon.Empleado;
import com.biosis.biosislite.entidades.inventario.Bien_Inventario;
import com.biosis.biosislite.entidades.inventario.Inventario;
import com.biosis.biosislite.entidades.inventario.InventarioAmbiente;
import com.biosis.biosislite.entidades.inventario.Movimiento;
import com.biosis.biosislite.vistas.dialogos.inventario.DlgAmbienteBusqueda;
import com.biosis.biosislite.vistas.dialogos.inventario.DlgInventarioSeleccion;
import com.biosis.biosislite.vistas.modelos.MTStock;
import com.biosis.biosislite.vistas.modelos.MTTraza;
import com.biosis.biosislite.vistas.modelos.MTimpresion;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Documentos
 */
public class VistaImprimir extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaVerMovimientos
     */
    private MovimientoControlador dmc;
    private Empleado empleado;
    private List<Bien_Inventario> lista;
    private BienInventarioControlador bic = new BienInventarioControlador();
    private Inventario inventario;

    private InventarioAmbiente ambiente;

    public VistaImprimir() {
        this.dmc = new MovimientoControlador();
        initComponents();
        listar();

        FormularioUtil.activarComponente(ambienteField, false);
        FormularioUtil.activarComponente(btnBuscar, false);
        FormularioUtil.activarComponente(btnInventario, false);
        FormularioUtil.activarComponente(btnAmbiente, false);

    }

    private static VistaImprimir instancia;

    public static VistaImprimir getInstancia() {
        if (instancia == null) {
            instancia = new VistaImprimir();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtInventario = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        ambienteField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImprimir = new org.jdesktop.swingx.JXTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnInventario = new javax.swing.JRadioButton();
        btnAmbiente = new javax.swing.JRadioButton();

        buttonGroup1.add(btnInventario);
        buttonGroup1.add(btnAmbiente);

        setClosable(true);
        setTitle("Imprimir etiquetas /código de barras");
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0};
        getContentPane().setLayout(layout);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel6.setText("Seleccionar inventario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtInventario, gridBagConstraints);

        jButton6.setIcon(new javax.swing.ImageIcon("img/iconos/Search.png"));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButton6, gridBagConstraints);

        jButton7.setIcon(new javax.swing.ImageIcon("img/iconos/clear.png"));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButton7, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(btnBuscar, gridBagConstraints);

        ambienteField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ambienteFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(ambienteField, gridBagConstraints);

        jLabel1.setText("Seleccionar ambiente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        tblImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblImprimirMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblImprimir);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jButton12.setIcon(new javax.swing.ImageIcon("img/iconos/Search.png"));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jButton12, gridBagConstraints);

        jButton13.setIcon(new javax.swing.ImageIcon("img/iconos/clear.png"));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jButton13, gridBagConstraints);

        btnInventario.setText("Imprimir por inventario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel1.add(btnInventario, gridBagConstraints);

        btnAmbiente.setText("Imprimir por ambiente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel1.add(btnAmbiente, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DlgInventarioSeleccion inventarioDialog = new DlgInventarioSeleccion(this);

        Inventario inventarioFloat = inventarioDialog.getInventario();

        if (inventarioFloat != null) {
            inventario = inventarioFloat;
            txtInventario.setText(inventario.getNombre());

            FormularioUtil.activarComponente(ambienteField, true);
            FormularioUtil.activarComponente(btnBuscar, true);
            FormularioUtil.activarComponente(btnInventario, true);
            FormularioUtil.activarComponente(btnAmbiente, true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        txtInventario.setText(null);
        inventario = null;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
        //        lista.addAll(this.empleadoControlador.buscarXNombre(txtBusqueda.getText().toUpperCase()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void ambienteFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ambienteFieldKeyPressed
        // TODO add your handling code here:

//        int code = evt.getKeyCode();
//        if (!(ambienteField.getText().equals("")) && code == KeyEvent.VK_ENTER) {
//            buscar();
//        }
    }//GEN-LAST:event_ambienteFieldKeyPressed

    private void tblImprimirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImprimirMouseReleased
        // TODO add your handling code here:
        //        int fila = tblBien.getSelectedRow();
        //        if (fila != -1) {
        //            Vacacion vacacion = listado.get(fila);
        //
        //            mostrar(vacacion);
        //        }
    }//GEN-LAST:event_tblImprimirMouseReleased

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DlgAmbienteBusqueda ambienteDialog = new DlgAmbienteBusqueda(this, this.inventario);

        this.ambiente = ambienteDialog.getAmbiente();

        if (this.ambiente != null) {
            ambienteField.setText(this.ambiente.getAmbiente().toString());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ambienteField;
    private javax.swing.JRadioButton btnAmbiente;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JRadioButton btnInventario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable tblImprimir;
    private javax.swing.JTextField txtInventario;
    // End of variables declaration//GEN-END:variables

    private void listar() {
//        lista = this.dmc.buscarTodos();
        lista = new ArrayList();
        lista = ObservableCollections.observableList(lista);

        MTimpresion mt = new MTimpresion(lista);
        tblImprimir.setModel(mt);

        actualizarTabla();
    }

    private void actualizarTabla() {
        tblImprimir.packAll();
    }

    private void buscar() {

        lista.clear();
        if (btnInventario.isSelected()) {
            lista.addAll(this.bic.buscarXImpresion(this.inventario));
            tblImprimir.packAll();
        } else if (btnAmbiente.isSelected()) {
            lista.addAll(this.bic.buscarXImpresion(this.inventario, this.ambiente));
            tblImprimir.packAll();
        }

    }

}
