/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.biosislite.vistas.inventario;

import com.biosis.biosislite.entidades.inventario.Inventario;
import com.biosis.biosislite.controladores.inventario.AbstractControlador;
import com.biosis.biosislite.controladores.inventario.InventarioControlador;
import com.biosis.biosislite.vistas.dialogos.inventario.DlgNuevoInventario;
import com.biosis.biosislite.vistas.dialogos.inventario.DlgSeleccionAmbientes;
import com.biosis.biosislite.vistas.modelos.MTInventario;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Documentos
 */
public class VistaInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inventario
     */
    public VistaInventario() {
        initComponents();
        bindeoSalvaje();
    }

    private static VistaInventario instancia;

    public static VistaInventario getInstancia() {
        if (instancia == null) {
            instancia = new VistaInventario();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoFiltro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        rdnNombre = new javax.swing.JRadioButton();
        rdnFechas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventarios = new org.jdesktop.swingx.JXTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        grupoFiltro.add(rdnNombre);
        grupoFiltro.add(rdnFechas);

        setClosable(true);
        setTitle("Proceso de Inventario");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 7, 0};
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventarios"));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0};
        jPanel2.setLayout(jPanel2Layout);

        dcFechaInicio.setMinimumSize(new java.awt.Dimension(135, 20));
        dcFechaInicio.setPreferredSize(new java.awt.Dimension(135, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(dcFechaInicio, gridBagConstraints);

        dcFechaFin.setMinimumSize(new java.awt.Dimension(135, 20));
        dcFechaFin.setPreferredSize(new java.awt.Dimension(135, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(dcFechaFin, gridBagConstraints);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(jTextField1, gridBagConstraints);

        rdnNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(rdnNombre, gridBagConstraints);

        rdnFechas.setText("Fechas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(rdnFechas, gridBagConstraints);

        tblInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblInventariosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel3.add(jButton2, gridBagConstraints);

        jButton3.setText("Continuar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jButton3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int accion;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        accion = AbstractControlador.NUEVO;
        ic.prepararCrear();

        DlgNuevoInventario nuevoI = new DlgNuevoInventario(this, ic.getSeleccionado(), accion);
        nuevoI.setVisible(true);
        buscar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int fila = this.tblInventarios.getSelectedRow();
        if (fila != -1) {
            ic.setSeleccionado(lista.get(fila));

            DlgSeleccionAmbientes ambientes = new DlgSeleccionAmbientes(this, ic.getSeleccionado());
            ambientes.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento de la lista", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private InventarioControlador ic = new InventarioControlador();

    

    private void buscar(Date inicio, Date fin) {

        List<Inventario> listaGeneral = ic.buscarXFechas(inicio, fin);
        lista.clear();
        lista.addAll(listaGeneral);
    }
    
    private void buscar() {

        List<Inventario> listaGeneral = ic.buscarTodos();
        lista.clear();
        lista.addAll(listaGeneral);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormularioUtil.activarComponente(dcFechaInicio, rdnFechas.isSelected());
        FormularioUtil.activarComponente(dcFechaFin, rdnFechas.isSelected());

        if (rdnFechas.isSelected()) {
            buscar(dcFechaInicio.getDate(), dcFechaFin.getDate());
        }else if(rdnNombre.isSelected()){
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblInventariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventariosMouseReleased
        // TODO add your handling code here:
        //        int fila = tblBien.getSelectedRow();
        //        if (fila != -1) {
            //            Vacacion vacacion = listado.get(fila);
            //
            //            mostrar(vacacion);
            //        }
    }//GEN-LAST:event_tblInventariosMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.ButtonGroup grupoFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdnFechas;
    private javax.swing.JRadioButton rdnNombre;
    private org.jdesktop.swingx.JXTable tblInventarios;
    // End of variables declaration//GEN-END:variables

    List<Inventario> lista;

    private void bindeoSalvaje() {

        lista = ic.buscarTodos();
        lista = ObservableCollections.observableList(lista);

//        JTableBinding bindeoDetalle = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, lista, tblInventarios);
//
////        BeanProperty bId = BeanProperty.create("Id");
//        BeanProperty bNombre = BeanProperty.create("nombre");
//        BeanProperty bPeriodo = BeanProperty.create("periodo");
//        BeanProperty bFInicio = BeanProperty.create("fecha_inicio");
//        BeanProperty bFFin = BeanProperty.create("fecha_fin");
//        BeanProperty bEstado = BeanProperty.create("estado");
//
////        bindeoDetalle.addColumnBinding(bId).setColumnName("ID").setEditable(false);
//        bindeoDetalle.addColumnBinding(bNombre).setColumnName("NOMBRE").setEditable(false);
//        bindeoDetalle.addColumnBinding(bPeriodo).setColumnName("PERIODO").setEditable(false);
//        bindeoDetalle.addColumnBinding(bFInicio).setColumnName("FECHA INICIO").setEditable(false);
//        bindeoDetalle.addColumnBinding(bFFin).setColumnName("FECHA FIN").setEditable(false);
//        bindeoDetalle.addColumnBinding(bEstado).setColumnName("ESTADO").setEditable(false);
//
//        bindeoDetalle.bind();
        
        MTInventario mt = new MTInventario(lista);
        tblInventarios.setModel(mt);
        
        tblInventarios.packAll();

    }
}
