/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.biosislite.vistas.dialogos;

import com.biosis.biosislite.controladores.AsignacionNGSControlador;
import com.biosis.biosislite.controladores.ConceptoControlador;
import com.biosis.biosislite.controladores.Controlador;
import com.biosis.biosislite.controladores.EmpleadoControlador;
import com.biosis.biosislite.controladores.GradoControlador;
import com.biosis.biosislite.controladores.NivelControlador;
import com.biosis.biosislite.controladores.SeccionControlador;
import com.biosis.biosislite.entidades.Concepto;
import com.biosis.biosislite.entidades.educativo.AsignacionNGS;
import com.biosis.biosislite.entidades.educativo.Grado;
import com.biosis.biosislite.entidades.educativo.Nivel;
import com.biosis.biosislite.entidades.educativo.Seccion;
import com.biosis.biosislite.entidades.escalafon.Empleado;
import com.personal.utiles.FormularioUtil;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JInternalFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Aldo
 */
public class DlgAsignacionSeccion extends javax.swing.JDialog {

    /**
     * Creates new form DlgAsignacionSeccion
     * @param parent
     * @param empleado
     */
    //
    private int accion;
    private AsignacionNGS asignacion;
    private final Empleado empleado;
    //Controladores
    private EmpleadoControlador ec;
    private NivelControlador nc;
    private GradoControlador gc;
    private SeccionControlador sc;
    private AsignacionNGSControlador asigc;
    private final ConceptoControlador cptc = ConceptoControlador.getInstance();
    
    
    public DlgAsignacionSeccion(JInternalFrame parent, Empleado empleado, int accion) {
        super(JOptionPane.getFrameForComponent(parent), true);
        initComponents();
        inicializar();
        bind();
        this.empleado = empleado;
        lblNombrePersona.setText(empleado.getPaterno()+' '+empleado.getMaterno()+' '+empleado.getNombre());
        this.accion = accion;
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlAsignacionSeccion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboNivel = new javax.swing.JComboBox();
        cboGrado = new javax.swing.JComboBox();
        cboSeccion = new javax.swing.JComboBox();
        cboTarea = new javax.swing.JComboBox();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNombrePersona = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignación de Sección");

        pnlAsignacionSeccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de asignación"));
        java.awt.GridBagLayout pnlAsignacionSeccionLayout = new java.awt.GridBagLayout();
        pnlAsignacionSeccionLayout.columnWidths = new int[] {0, 8, 0, 8, 0};
        pnlAsignacionSeccionLayout.rowHeights = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        pnlAsignacionSeccion.setLayout(pnlAsignacionSeccionLayout);

        jLabel1.setText("Nivel:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlAsignacionSeccion.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Grado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlAsignacionSeccion.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Sección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlAsignacionSeccion.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Tarea:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlAsignacionSeccion.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Fecha de inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlAsignacionSeccion.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Fecha de fin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlAsignacionSeccion.add(jLabel6, gridBagConstraints);

        cboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNivelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlAsignacionSeccion.add(cboNivel, gridBagConstraints);

        cboGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGradoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlAsignacionSeccion.add(cboGrado, gridBagConstraints);

        cboSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSeccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlAsignacionSeccion.add(cboSeccion, gridBagConstraints);

        cboTarea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlAsignacionSeccion.add(cboTarea, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlAsignacionSeccion.add(dcFechaInicio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlAsignacionSeccion.add(dcFechaFin, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        pnlAsignacionSeccion.add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        pnlAsignacionSeccion.add(lblNombrePersona, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAsignacionSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAsignacionSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(!hayErrores()){
            guardar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNivelActionPerformed
        // TODO add your handling code here:
        if(((Nivel)cboNivel.getSelectedItem())!=null){
        
            gradoList = ((Nivel)cboNivel.getSelectedItem()).getGradoList();
            JComboBoxBinding bindingCondicion = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, gradoList, cboGrado);
            bindingCondicion.bind();
            cboGrado.setRenderer(new DefaultListCellRenderer(){
                @Override
                public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    if (value instanceof Grado) {
                        value = ((Grado) value).getAbreviatura();
                    }
                    return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                }
            }); 
        }
    }//GEN-LAST:event_cboNivelActionPerformed

    private void cboGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGradoActionPerformed
        // TODO add your handling code here:
        if((Grado)cboGrado.getSelectedItem()!=null){
        
        seccionList = ((Grado)cboGrado.getSelectedItem()).getSeccionList();
        JComboBoxBinding bindingCondicion = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, seccionList, cboSeccion);
        bindingCondicion.bind();
        cboSeccion.setRenderer(new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof Seccion) {
                    value = ((Seccion) value).getAbreviatura();
                }
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            }
        });
        }
    }//GEN-LAST:event_cboGradoActionPerformed

    private void cboSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSeccionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboGrado;
    private javax.swing.JComboBox cboNivel;
    private javax.swing.JComboBox cboSeccion;
    private javax.swing.JComboBox cboTarea;
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombrePersona;
    private javax.swing.JPanel pnlAsignacionSeccion;
    // End of variables declaration//GEN-END:variables

    private void inicializar(){
        ec = new EmpleadoControlador();
        asigc = new AsignacionNGSControlador();
        nc = new NivelControlador();
        gc = new GradoControlador();
        sc = new SeccionControlador();
    }
    
    private List<Nivel> nivelList;
    private List<Grado> gradoList;
    private List<Seccion> seccionList;
    
    private void bind(){
//        cboNivel.setModel(new DefaultComboBoxModel(cptc.buscarXPrefijo(1).toArray()));
//        cboNivel.setRenderer(new DefaultListCellRenderer(){
//            @Override
//            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
//                if (value instanceof Concepto) {
//                    value = ((Concepto) value).getDescripcion();
//                }
//                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); //To change body of generated methods, choose Tools | Templates.
//            }
//        });
        nivelList = nc.buscarTodos();
        JComboBoxBinding bindingCondicion = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, nivelList, cboNivel);
        bindingCondicion.bind();
        cboNivel.setRenderer(new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof Nivel) {
                    value = ((Nivel) value).getNombre();
                }
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            }
        });
//        cboGrado.setModel(new DefaultComboBoxModel(cptc.buscarXPrefijo(2).toArray()));
//        cboGrado.setRenderer(new DefaultListCellRenderer(){
//            @Override
//            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
//                if (value instanceof Concepto) {
//                    value = ((Concepto) value).getDescripcion();
//                }
//                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); //To change body of generated methods, choose Tools | Templates.
//            }
//        });
//        cboSeccion.setModel(new DefaultComboBoxModel(cptc.buscarXPrefijo(3).toArray()));
//        cboSeccion.setRenderer(new DefaultListCellRenderer(){
//            @Override
//            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
//                if (value instanceof Concepto) {
//                    value = ((Concepto) value).getDescripcion();
//                }
//                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); //To change body of generated methods, choose Tools | Templates.
//            }
//        });
        cboTarea.setModel(new DefaultComboBoxModel(cptc.buscarXPrefijo(15).toArray()));
        cboTarea.setRenderer(new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof Concepto) {
                    value = ((Concepto) value).getDescripcion();
                }
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }
    
    private boolean hayErrores() {
        //COMPROBAMOS LOS DISTINTOS TIPOS
        int errores = 0;
        Date fechaInicio = dcFechaInicio.getDate();

        String mensajeError = "";
        Date fechaFin = dcFechaFin.getDate();
            if (fechaInicio.compareTo(fechaFin) > 0) {
                errores++;
                mensajeError = ">La fecha de inicio debe ser menor que la fecha de fin\n";
            }
        if (errores > 0) {
            JOptionPane.showMessageDialog(this, mensajeError, "Mensaje del sistema", JOptionPane.WARNING_MESSAGE);
        }
        return errores != 0;
    }

    private void guardar(){
        if (FormularioUtil.dialogoConfirmar(this, accion)) {
            asignacion = new AsignacionNGS();
            asignacion.setResponsable(this.empleado);
            
            asignacion.setNivel(((Nivel)cboNivel.getSelectedItem()));
            asignacion.setGrado(((Grado)cboGrado.getSelectedItem()));
            asignacion.setSeccion(((Seccion)cboSeccion.getSelectedItem()));
            asignacion.setFechaInicio(dcFechaInicio.getDate());
            asignacion.setFechaFin(dcFechaFin.getDate());
            asignacion.setTipo(((Concepto)cboTarea.getSelectedItem()).getId().getCorrelativo());
//          
            asigc.setSeleccionado(asignacion);
            if (asigc.accion(accion)) {
                FormularioUtil.mensajeExito(this, accion);

                this.dispose();

            } else {
                FormularioUtil.mensajeError(this, accion);
            }
        }
    }
}
